### ISSUE TITLE
Self-Assessment checklist - QA and Completion

### ISSUE THREAD

**Issue by stephen-rowan** [Quality-Assurance-DAO/F5-Developer-ecosystem-Proposal#95]
# The Self-Assessment Checklist

#### A
- [x] - A. Received emails from communications@iohk.io
#### B
- [x] - B. Submitted this proposal to only one challenge.

#### C
- [x] - C. How my proposal impacts the challenge metrics.

How my proposal impacts the challenge metrics is articulated in the comments beneath each box checked below.

#### The challenge metrics in F5: Developer ecosystem are -
- [x] - At the end of this challenge, we will be asking ourselves: Did we manage to make it easier for developers to build on top of Cardano?

I hope to highlight this in Output (3) Open-Source Assessment Report  that an improved awareness of the wide range of the open-source Cardano community may enable developers to build from many different even contrary directions. 

- [x] - Filling in gaps defined in the exploration stage.
- [x] - Number of developers actively building on top of Cardano

- [x] - Number of repos on Github using the tooling. (Month over month increase)

The tooling in this proposal, the repo, _is_ the proposal undone. It will offer a deconstructed, dissected and resurrected F5-Developer-ecosystem-Proposal. Although not usable as a template - it is hoped it's bones may be picked over for many months to come as point of reference.

- [x] - Reduce wait time of unanswered communications with developers to 24 hours.

- [x] -A sense of community and conversations. Having people around to talk with.

This proposal has _already_ been circulated around the Catalyst open-source community, provoking mixed reactions and conversations. 

#### D
- [x] - D. How I address the challenge question.

I addressed the challenge question "How can we create a positive developer experience that helps the developer focus on building successful apps?" by focusing on one instance of a development lifecycle ; how to take something broken to the community to fix.

#### E
- [x] - E. Definition of Success after 3, 6 and 12 months.

Definitions of Success :

3 Months - The Proposal is funded, it's contribution is recognized, which provided an incentive to continue to Fund 7.

6 Months - The Proposal is used as a useful reference tool for other proposals.

12 Months - The Proposal is now redundant and regarded as a historical anomaly.

#### F
- [x] - F. Broken down my Budget Requirements.

My Budget is broken into $5 for basic costs. The minting of an ADA Non-Fungible Token is pending negotiation for work in kind with NFT-DAO.

#### G
- [x] - G. Include identifying information about all proposers.

The repository maintainer Stephen Whitenstall https://stephen-rowan.github.io/

#### H
- [x] - H. Defined Expected Launch Date.

11/04/2021 (Alpha Version 0.0 - Released) through 26/05/2021 (Release of Alpha Version 2.0) to Governance : Due : TBA (by Project Catalyst).

### General Usability : 

1. The Self-Assessment Checklist is not visible when not editing your proposal - so to the initiated it appears to have disappeared.
2. When the Self-Assessment Checklist is visible (when editing your proposal) - the displayed text is truncated.
3. Whilst a tool tip displays the full text of the truncated Checklist item - there is a temptation to click on the item.
4. Clicking on an item in this way could lead to incorrect answers - where a proposer has clicked on an item by mistake and forgets to review.

### I confirm that I have ... (QA)

- [x] - A. Received emails from communications@iohk.io

This question seems to have generated the greatest confusion. Which emails ? When ? From whom ? For what purpose ?

- [x] - B. Submitted this proposal to only one challenge.

### I have articulated in my proposal ...

- [x] - C. How my proposal impacts the challenge metrics.

What metrics ? Where can they be found ?

- [x] - D. How I address the challenge question.

A more specific reference to the challenge question might be helpful

- [x] - E. Definition of Success after 3, 6 and 12 months.

Quite Clear

- [x] - F. Broken down my Budget Requirements.

Quite Clear

- [x] - G. Include identifying information about all proposers.

Quite Clear. Although define "identifying information" ?

- [x] - H. Defined Expected Launch Date.
 
Quite Clear
